### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by ksmyth** [metamorph-inc/testbenchexecutor#2]
echo ./venv/Scripts/nosetests > test.sh
git bisect start
git bisect good 5d965a797d29f7bd6f10ef5898beee04f7649914
git bisect bad HEAD
git bisect run bash test.sh

9b2120b624ead3fd0935ae8c4d8d339fcade407b is the first bad commit
commit 9b2120b624ead3fd0935ae8c4d8d339fcade407b
Author: Jonathon Williams <jwilliams@metamorphsoftware.com>
Date:   Thu Jan 4 17:05:40 2018 -0600

    OPENMETA-359 HTML report generation

**Comment by jonathonw** [comment]
The only test failure I'm seeing is in `test_executor_run_all`, with the error:

    Running '[u'dir', u'.']'
    [Error 2] The system cannot find the file specified

Fixed in 65cb5a3 by calling `cmd /c dir` instead of just `dir`.

Are you seeing other failures?  Because the failure above didn't start at 9b2120b (it's present in the previous commit, too).

**Comment by ksmyth** [comment]
https://ci.appveyor.com/project/Metamorph/testbenchexecutor

**Comment by jonathonw** [comment]
Fixed in 985d96f (needed to construct full paths to the step log files).
